task: MNIST_FedAvg
random_seed: 0


batch_size: 10
test_batch_size: 100
lr: 0.01
momentum: 0.9
decay: 0.0001
epochs: 300
save_on_epochs: [100, 200, 300]
optimizer: SGD
log_interval: 100

loss_balance: fixed
fixed_scales: {'backdoor': 0.5, 'normal': 0.5}

save_model: True
log: True
tb: True

transform_train: False

fl_client_train_ratio: 0.9091
fl_no_models: 10
fl_total_participants: 30

fl_eta: 1
fl_q: 0.1
fl_number_of_adversaries: 0
fl_weight_scale: 0


loss_tasks:
  - normal
